# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            CritBear
description:      '<a href="http://www.kyunghee.edu" target="_blank">'
url:              http://critbear.github.io
baseurl:          /

author:
  name:           'Kim KyoungMin'
  url:            https://critbear.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/CritBear/critbear.github.io
