# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            CritBear
description:      'A student at <a href="http://www.kyunghee.edu" target="_blank">KyoungHee University</a> and belongs to the club <a href="https://retr0.io" target="_blank">retr0</a>'
url:              http://critbear.github.io
baseurl:          /

author:
  name:           'Kim KyoungMin'
  url:            https://critbear.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/CritBear/critbear.github.io
