/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cube.glb -t
Author: TheMtnDewback (https://sketchfab.com/TheMtnDewback)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/rubiks-cube-3577f5154ef74fe5923d27ac3f581e9e
Title: Rubik's Cube
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_27: THREE.Mesh
    Object_29: THREE.Mesh
    Object_31: THREE.Mesh
    Object_33: THREE.Mesh
    Object_35: THREE.Mesh
    Object_37: THREE.Mesh
    Object_39: THREE.Mesh
    Object_41: THREE.Mesh
    Object_43: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_58: THREE.Mesh
    Object_60: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
  }
  materials: {
    material_0: THREE.MeshPhysicalMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cube.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.31, 0]}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} position={[0, -0.31, 0]} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} position={[0, -0.31, 0]} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.material_0} position={[0, -0.31, 0]} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.material_0} position={[0, -0.31, 0]} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.material_0} position={[0, -0.31, 0]} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.material_0} position={[0, -0.31, 0]} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.material_0} position={[0, -0.31, 0]} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.material_0} position={[0, -0.31, 0]} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.material_0} position={[0, -0.31, 0]} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.material_0} position={[0, -0.31, 0]} />
      </group>
      <group position={[0, -0.31, 0]}>
        <mesh geometry={nodes.Object_46.geometry} material={materials.material_0} position={[0, 0.31, 0]} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.material_0} position={[0, 0.31, 0]} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.material_0} position={[0, 0.31, 0]} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.material_0} position={[0, 0.31, 0]} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.material_0} position={[0, 0.31, 0]} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.material_0} position={[0, 0.31, 0]} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.material_0} position={[0, 0.31, 0]} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.material_0} position={[0, 0.31, 0]} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.material_0} position={[0, 0.31, 0]} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.material_0} position={[0, 0.31, 0]} />
      </group>
      <mesh geometry={nodes.Object_27.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.material_0} />
    </group>
  )
}

useGLTF.preload('/cube.glb')
