/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 test.glb -t
Author: Ricardo Rivera (https://sketchfab.com/Ricardo_Rivera)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/loz-adventurers-camp-statue-e4a4d094e395466e9e5dded09c765708
Title: LoZ Adventurer's Camp - Statue
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Statue_Statue_0: THREE.Mesh
    Statue_Statue_0_1: THREE.Mesh
    Statue_Statue_0_2: THREE.Mesh
  }
  materials: {
    Statue: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/test.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Statue_Statue_0.geometry} material={materials.Statue} />
      <mesh geometry={nodes.Statue_Statue_0_1.geometry} material={materials.Statue} />
      <mesh geometry={nodes.Statue_Statue_0_2.geometry} material={materials.Statue} />
    </group>
  )
}

useGLTF.preload('/test.glb')
